// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAnimal(arg1:main.Animal):Promise<void>;

export function AddCorral(arg1:main.Corral):Promise<void>;

export function AddInsumo(arg1:main.Insumo):Promise<void>;

export function AddSeguimientoPeso(arg1:main.SeguimientoPeso):Promise<void>;

export function AddTarea(arg1:main.Tarea):Promise<void>;

export function AddUser(arg1:main.User):Promise<void>;

export function ChangePassword(arg1:string,arg2:string):Promise<void>;

export function CompletarTarea(arg1:string):Promise<void>;

export function ConfirmarUltrasonido(arg1:string,arg2:boolean,arg3:number):Promise<void>;

export function CrearRecetaVeterinaria(arg1:main.RecetaVeterinaria):Promise<void>;

export function DeleteAnimal(arg1:string):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function GetAnimales():Promise<Array<main.Animal>>;

export function GetCorrales():Promise<Array<main.Corral>>;

export function GetCurrentUser():Promise<main.User>;

export function GetDiagnosticosGestacion(arg1:string):Promise<Array<main.DiagnosticoGestacion>>;

export function GetHistorialClinico(arg1:string):Promise<Array<Record<string, any>>>;

export function GetInsumos():Promise<Array<main.Insumo>>;

export function GetPartos(arg1:string):Promise<Array<main.Parto>>;

export function GetRecetas(arg1:string):Promise<Array<main.RecetaVeterinaria>>;

export function GetSeguimientosPeso(arg1:string):Promise<Array<main.SeguimientoPeso>>;

export function GetStats():Promise<Record<string, any>>;

export function GetTareas():Promise<Array<main.Tarea>>;

export function GetUsers():Promise<Array<main.User>>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function MoverAnimal(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RegistrarDiagnosticoGestacion(arg1:main.DiagnosticoGestacion):Promise<void>;

export function RegistrarEventoReproductivo(arg1:main.EventoReproductivo):Promise<void>;

export function RegistrarParto(arg1:main.Parto):Promise<void>;

export function RegistrarTratamiento(arg1:main.Tratamiento):Promise<void>;

export function StartAPIServer(arg1:number):Promise<void>;

export function UpdateAnimal(arg1:main.Animal):Promise<void>;

export function UpdateUser(arg1:main.User):Promise<void>;
