// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAnimal(arg1) {
  return window['go']['main']['App']['AddAnimal'](arg1);
}

export function AddCorral(arg1) {
  return window['go']['main']['App']['AddCorral'](arg1);
}

export function AddInsumo(arg1) {
  return window['go']['main']['App']['AddInsumo'](arg1);
}

export function AddSeguimientoPeso(arg1) {
  return window['go']['main']['App']['AddSeguimientoPeso'](arg1);
}

export function AddTarea(arg1) {
  return window['go']['main']['App']['AddTarea'](arg1);
}

export function AddUser(arg1) {
  return window['go']['main']['App']['AddUser'](arg1);
}

export function ChangePassword(arg1, arg2) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2);
}

export function CompletarTarea(arg1) {
  return window['go']['main']['App']['CompletarTarea'](arg1);
}

export function ConfirmarUltrasonido(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConfirmarUltrasonido'](arg1, arg2, arg3);
}

export function CrearRecetaVeterinaria(arg1) {
  return window['go']['main']['App']['CrearRecetaVeterinaria'](arg1);
}

export function DeleteAnimal(arg1) {
  return window['go']['main']['App']['DeleteAnimal'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function GetAnimales() {
  return window['go']['main']['App']['GetAnimales']();
}

export function GetCorrales() {
  return window['go']['main']['App']['GetCorrales']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDiagnosticosGestacion(arg1) {
  return window['go']['main']['App']['GetDiagnosticosGestacion'](arg1);
}

export function GetHistorialClinico(arg1) {
  return window['go']['main']['App']['GetHistorialClinico'](arg1);
}

export function GetInsumos() {
  return window['go']['main']['App']['GetInsumos']();
}

export function GetIsDemoMode() {
  return window['go']['main']['App']['GetIsDemoMode']();
}

export function GetPartos(arg1) {
  return window['go']['main']['App']['GetPartos'](arg1);
}

export function GetRecetas(arg1) {
  return window['go']['main']['App']['GetRecetas'](arg1);
}

export function GetSeguimientosPeso(arg1) {
  return window['go']['main']['App']['GetSeguimientosPeso'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTareas() {
  return window['go']['main']['App']['GetTareas']();
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function ImportAnimalsExcel(arg1) {
  return window['go']['main']['App']['ImportAnimalsExcel'](arg1);
}

export function ImportAnimalsExcelData(arg1) {
  return window['go']['main']['App']['ImportAnimalsExcelData'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function MoverAnimal(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoverAnimal'](arg1, arg2, arg3);
}

export function RegistrarDiagnosticoGestacion(arg1) {
  return window['go']['main']['App']['RegistrarDiagnosticoGestacion'](arg1);
}

export function RegistrarEventoReproductivo(arg1) {
  return window['go']['main']['App']['RegistrarEventoReproductivo'](arg1);
}

export function RegistrarParto(arg1) {
  return window['go']['main']['App']['RegistrarParto'](arg1);
}

export function RegistrarTratamiento(arg1) {
  return window['go']['main']['App']['RegistrarTratamiento'](arg1);
}

export function StartAPIServer(arg1) {
  return window['go']['main']['App']['StartAPIServer'](arg1);
}

export function SyncToJarvis() {
  return window['go']['main']['App']['SyncToJarvis']();
}

export function ToggleDemoMode(arg1) {
  return window['go']['main']['App']['ToggleDemoMode'](arg1);
}

export function UpdateAnimal(arg1) {
  return window['go']['main']['App']['UpdateAnimal'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['main']['App']['UpdateUser'](arg1);
}
